// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: order.proto

package order

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ApplyOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (x *ApplyOrderRequest) Reset() {
	*x = ApplyOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOrderRequest) ProtoMessage() {}

func (x *ApplyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOrderRequest.ProtoReflect.Descriptor instead.
func (*ApplyOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyOrderRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

type ApplyOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql        string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	ApplyOrder string `protobuf:"bytes,2,opt,name=applyOrder,proto3" json:"applyOrder,omitempty"`
}

func (x *ApplyOrderResponse) Reset() {
	*x = ApplyOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOrderResponse) ProtoMessage() {}

func (x *ApplyOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOrderResponse.ProtoReflect.Descriptor instead.
func (*ApplyOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyOrderResponse) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ApplyOrderResponse) GetApplyOrder() string {
	if x != nil {
		return x.ApplyOrder
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

var file_order_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x25, 0x0a, 0x11, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c, 0x22, 0x46, 0x0a, 0x12, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x73, 0x71, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x32, 0x6a, 0x0a, 0x19, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x4f, 0x70,
	0x74, 0x6d, 0x69, 0x7a, 0x65, 0x72, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x4d, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData = file_order_proto_rawDesc
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_proto_rawDescData)
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_proto_goTypes = []interface{}{
	(*ApplyOrderRequest)(nil),  // 0: order.ApplyOrderRequest
	(*ApplyOrderResponse)(nil), // 1: order.ApplyOrderResponse
}
var file_order_proto_depIdxs = []int32{
	0, // 0: order.LogicalOptmizerApplyOrder.getApplyOrderRequest:input_type -> order.ApplyOrderRequest
	1, // 1: order.LogicalOptmizerApplyOrder.getApplyOrderRequest:output_type -> order.ApplyOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_rawDesc = nil
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LogicalOptmizerApplyOrderClient is the client API for LogicalOptmizerApplyOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogicalOptmizerApplyOrderClient interface {
	GetApplyOrderRequest(ctx context.Context, in *ApplyOrderRequest, opts ...grpc.CallOption) (*ApplyOrderResponse, error)
}

type logicalOptmizerApplyOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewLogicalOptmizerApplyOrderClient(cc grpc.ClientConnInterface) LogicalOptmizerApplyOrderClient {
	return &logicalOptmizerApplyOrderClient{cc}
}

func (c *logicalOptmizerApplyOrderClient) GetApplyOrderRequest(ctx context.Context, in *ApplyOrderRequest, opts ...grpc.CallOption) (*ApplyOrderResponse, error) {
	out := new(ApplyOrderResponse)
	err := c.cc.Invoke(ctx, "/order.LogicalOptmizerApplyOrder/getApplyOrderRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogicalOptmizerApplyOrderServer is the server API for LogicalOptmizerApplyOrder service.
type LogicalOptmizerApplyOrderServer interface {
	GetApplyOrderRequest(context.Context, *ApplyOrderRequest) (*ApplyOrderResponse, error)
}

// UnimplementedLogicalOptmizerApplyOrderServer can be embedded to have forward compatible implementations.
type UnimplementedLogicalOptmizerApplyOrderServer struct {
}

func (*UnimplementedLogicalOptmizerApplyOrderServer) GetApplyOrderRequest(context.Context, *ApplyOrderRequest) (*ApplyOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplyOrderRequest not implemented")
}

func RegisterLogicalOptmizerApplyOrderServer(s *grpc.Server, srv LogicalOptmizerApplyOrderServer) {
	s.RegisterService(&_LogicalOptmizerApplyOrder_serviceDesc, srv)
}

func _LogicalOptmizerApplyOrder_GetApplyOrderRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogicalOptmizerApplyOrderServer).GetApplyOrderRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.LogicalOptmizerApplyOrder/GetApplyOrderRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogicalOptmizerApplyOrderServer).GetApplyOrderRequest(ctx, req.(*ApplyOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogicalOptmizerApplyOrder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.LogicalOptmizerApplyOrder",
	HandlerType: (*LogicalOptmizerApplyOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getApplyOrderRequest",
			Handler:    _LogicalOptmizerApplyOrder_GetApplyOrderRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
