# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lab.proto',
  package='mlpb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tlab.proto\x12\x04mlpb\"\\\n\x13NextApplyIdxRequest\x12\x0b\n\x03sql\x18\x01 \x01(\t\x12\x0e\n\x06reward\x18\x02 \x01(\x03\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\x0c\n\x04plan\x18\x04 \x01(\t\x12\x0c\n\x04\x66lag\x18\x05 \x01(\t\"4\n\x14NextApplyIdxResponse\x12\x0b\n\x03sql\x18\x01 \x01(\t\x12\x0f\n\x07ruleIdx\x18\x02 \x01(\x03\x32j\n\x15\x41utoLogicalRulesApply\x12Q\n\x16getNextApplyIdxRequest\x12\x19.mlpb.NextApplyIdxRequest\x1a\x1a.mlpb.NextApplyIdxResponse\"\x00\x62\x06proto3')
)




_NEXTAPPLYIDXREQUEST = _descriptor.Descriptor(
  name='NextApplyIdxRequest',
  full_name='mlpb.NextApplyIdxRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sql', full_name='mlpb.NextApplyIdxRequest.sql', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='mlpb.NextApplyIdxRequest.reward', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='mlpb.NextApplyIdxRequest.done', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plan', full_name='mlpb.NextApplyIdxRequest.plan', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flag', full_name='mlpb.NextApplyIdxRequest.flag', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=111,
)


_NEXTAPPLYIDXRESPONSE = _descriptor.Descriptor(
  name='NextApplyIdxResponse',
  full_name='mlpb.NextApplyIdxResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sql', full_name='mlpb.NextApplyIdxResponse.sql', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ruleIdx', full_name='mlpb.NextApplyIdxResponse.ruleIdx', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=165,
)

DESCRIPTOR.message_types_by_name['NextApplyIdxRequest'] = _NEXTAPPLYIDXREQUEST
DESCRIPTOR.message_types_by_name['NextApplyIdxResponse'] = _NEXTAPPLYIDXRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NextApplyIdxRequest = _reflection.GeneratedProtocolMessageType('NextApplyIdxRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEXTAPPLYIDXREQUEST,
  '__module__' : 'lab_pb2'
  # @@protoc_insertion_point(class_scope:mlpb.NextApplyIdxRequest)
  })
_sym_db.RegisterMessage(NextApplyIdxRequest)

NextApplyIdxResponse = _reflection.GeneratedProtocolMessageType('NextApplyIdxResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEXTAPPLYIDXRESPONSE,
  '__module__' : 'lab_pb2'
  # @@protoc_insertion_point(class_scope:mlpb.NextApplyIdxResponse)
  })
_sym_db.RegisterMessage(NextApplyIdxResponse)



_AUTOLOGICALRULESAPPLY = _descriptor.ServiceDescriptor(
  name='AutoLogicalRulesApply',
  full_name='mlpb.AutoLogicalRulesApply',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=167,
  serialized_end=273,
  methods=[
  _descriptor.MethodDescriptor(
    name='getNextApplyIdxRequest',
    full_name='mlpb.AutoLogicalRulesApply.getNextApplyIdxRequest',
    index=0,
    containing_service=None,
    input_type=_NEXTAPPLYIDXREQUEST,
    output_type=_NEXTAPPLYIDXRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOLOGICALRULESAPPLY)

DESCRIPTOR.services_by_name['AutoLogicalRulesApply'] = _AUTOLOGICALRULESAPPLY

# @@protoc_insertion_point(module_scope)
