# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lab_pb2 as lab__pb2


class AutoLogicalRulesApplyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getNextApplyIdxRequest = channel.unary_unary(
                '/lab.AutoLogicalRulesApply/getNextApplyIdxRequest',
                request_serializer=lab__pb2.NextApplyIdxRequest.SerializeToString,
                response_deserializer=lab__pb2.NextApplyIdxResponse.FromString,
                )


class AutoLogicalRulesApplyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getNextApplyIdxRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoLogicalRulesApplyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getNextApplyIdxRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.getNextApplyIdxRequest,
                    request_deserializer=lab__pb2.NextApplyIdxRequest.FromString,
                    response_serializer=lab__pb2.NextApplyIdxResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lab.AutoLogicalRulesApply', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AutoLogicalRulesApply(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getNextApplyIdxRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lab.AutoLogicalRulesApply/getNextApplyIdxRequest',
            lab__pb2.NextApplyIdxRequest.SerializeToString,
            lab__pb2.NextApplyIdxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
