# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import order_pb2 as order__pb2


class LogicalOptmizerApplyOrderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getApplyOrderRequest = channel.unary_unary(
                '/order.LogicalOptmizerApplyOrder/getApplyOrderRequest',
                request_serializer=order__pb2.ApplyOrderRequest.SerializeToString,
                response_deserializer=order__pb2.ApplyOrderResponse.FromString,
                )


class LogicalOptmizerApplyOrderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getApplyOrderRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogicalOptmizerApplyOrderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getApplyOrderRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.getApplyOrderRequest,
                    request_deserializer=order__pb2.ApplyOrderRequest.FromString,
                    response_serializer=order__pb2.ApplyOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'order.LogicalOptmizerApplyOrder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogicalOptmizerApplyOrder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getApplyOrderRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/order.LogicalOptmizerApplyOrder/getApplyOrderRequest',
            order__pb2.ApplyOrderRequest.SerializeToString,
            order__pb2.ApplyOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
